### ISSUE TITLE
Pull Request_Repo Update

### ISSUE THREAD

**Issue by emrebiyik** [MIT-Emerging-Talent/ET6-foundations-group-10#11]
In the Pull Request section, I have updated the repository due to the group documents being revised by @Evan. Approval is urgently needed.

Please review and approve promptly. Let’s ensure everything is up to date. 🚀

**Comment by oleksandr-maksymikhin** [comment]
Thre was another issue related to the Pull request for repository update. I have reviewd and merged it. It looks like there are two issues to the same task. I mark this issue as completed.
