### ISSUE TITLE
Set up repository

### ISSUE THREAD

**Issue by oleksandr-maksymikhin** [MIT-Emerging-Talent/ET6-foundations-group-10#2]
Set up ET6-foundations-group-10 repository to protect main, activate flows, add issues

**Comment by oleksandr-maksymikhin** [comment]
1. Activate Issues.
2. Activate flow IT CI checks.
3. Protect main branch:
- Require a code review for PRs main branch (1 person),
- Require approvals
- Dismiss stale pull request approvals when new commits are pushed
- Require approval of the most recent reviewable push
- Require conversation resolution before merging
- Do not allow bypassing the above settings

**Comment by oleksandr-maksymikhin** [comment]
There are some "IT CI checks" errors but they should be resolved once we start to add the code and tests. At list with code and test we will be able to analyse how does it work.

**Comment by emrebiyik** [comment]
The README.md file and the About section were missing, but I have completed them and submitted them for review. 🚀
