### ISSUE TITLE
IT CI checks issues

### ISSUE THREAD

**Issue by oleksandr-maksymikhin** [MIT-Emerging-Talent/ET6-foundations-group-10#3]
Resolve IT CI checks issues: md_formatting, py_tests

**Comment by emrebiyik** [comment]
As seen in the following link: https://github.com/MIT-Emerging-Talent/ET6-foundations-group-10/actions, the errors need to be reviewed and resolved, especially by those responsible for the changes in the main branch.

Please prioritize fixing these issues to ensure a smooth workflow and successful build processes. 😊
